#!/usr/bin/env bash
set -e

source "$(dirname "$0")/_helpers"

node_modules=$(find . -name 'node_modules' -type d -maxdepth 2)
for dir in $node_modules; do
  dir=$(dirname "$dir")
  echo "Removing node_modules in $dir"
  trash node_modules
done
package_files=$(find . -name 'package.json')

for file in $package_files; do
  dir=$(dirname "$file")
  if [[ $dir == *"node_modules"* ]]; then
    continue
  fi
  echo "Installing dependencies in $dir"
  cd "$dir"
  if [ -f "$dir/package-lock.json" ]; then
    npm ci
  else
    npm i
  fi
done
