#!/usr/bin/env node
const fs = require('fs-extra');
const path = require('path');
const fg = require('fast-glob');

const NPMIGNORE_TEMPLATE = `# .npmignore
*.log
**/__tests__/**
*.spec.js
.env
.env.test
.firebaserc
`;

const addNpmignore = async () => {
  const packages = await fg(['./packages/*'], {
    onlyFiles: false,
    onlyDirectories: true,
  });
  const packagesWithoutNpmignore = packages.filter((pkg) => {
    return !fs.existsSync(path.join(pkg, '.npmignore'));
  });
  const promises = packagesWithoutNpmignore.map(async (pkg) => {
    console.log(`Adding .npmignore to ${pkg}`);
    await fs.writeFile(path.join(pkg, '.npmignore'), NPMIGNORE_TEMPLATE);
  });
  await Promise.all(promises);
};

const generatePackage = async () => {
  await addNpmignore();
};

generatePackage().catch(console.error);
